public/status-helpers.js
marks items in the past as complete
=> use time for completion

pages/index.html.js, public/jira-oidc-helpers.js, public/timeline-report.js
=> adding errors and logout for #28

public/css/primitives.css, public/prepare-issues/prepare-issues.js, public/semver-releases.js, public/timeline-report.js, public/timeline-use.md
=> hide unknown initiatives and docs on timing

.github/workflows/deploy-pr.yaml, .github/workflows/deploy.yaml, .github/workflows/destroy-pr.yaml, .vscode/settings.json
Updated all workflows to use the latest version of the Docker to EC2 action, v1.0.1.
=> update all workflows to v1.0.1 of EC2 Action

.github/workflows/deploy.yaml
As per suggestion: https://bitovi.slack.com/archives/CB18EJU00/p1720110177333129?thread_ts=1720100290.223279&cid=CB18EJU00
=> Increase ec2_instance_size to t3.medium

CONTRIBUTING.md, pages/index.html.js, public/atlassian-connect.json
Also add instructions for connecting the app to CONTRIBUTING.md
=> [TR-34] Connect the app to Jira for local dev

public/jira/derived/readme.md, public/jira/normalized/readme.md, public/jira/raw/readme.md, public/jira/readme.md, public/jira/rollup/readme.md
This PR introduces _**readme**_ files for each module in the project (/raw, /normalized, /derived, /rollup). The goal is to provide clear explanations of the purpose and functionality of each module, as well as how they interact within the overall system.
Please review the content for accuracy and share any feedback or suggestions.
=> TR-60 - Add Initial Readme Files for each module 

public/stateful-data/jira-data-requests.js, public/timeline-configuration/state-helpers.js, public/timeline-configuration/timeline-configuration.js, rollup.config.mjs
This comments out the mounting of the "Teams" react component.  I'm not exactly sure why the configurationPromise would never resolve, my guess it that `normalizeOptions` wasn't present.  
If I had to guess again, it's likely because the Jira issue to contain those normalizeOptions wasn't ever created in the environment I'm testing in.  
@DavidNic11 , you should probably test and make sure things work if the issue is created or not.
=> rolling back teams to make sure things work

public/jira-oidc-helpers.ts, public/stateful-data/jira-data-requests.js
Progress indicators weren't working. This made it impossible to load children.
=> fixing progress indicators

public/shared/simple-tooltip.js
The was using the wrong method of getting the viewport dimensions
=> fixing the tooltip positioning

public/jira-oidc-helpers/jira.ts, public/jira/derived/work-status/work-status.ts, public/jira/derived/work-timing/work-timing.ts, public/jira/normalized/defaults.test.ts, public/jira/normalized/defaults.ts, public/jira/raw/rollback/rollback.ts, public/jira/rollup/percent-complete/percent-complete.js, public/jira/shared/types.ts, public/react/Configure/components/Teams/services/team-configuration/reconcile.ts, public/react/Configure/components/Teams/shared/normalize.ts, public/reports/gantt-grid.js, public/reports/table-grid.js, public/select-report-type/select-report-type.js, public/shared/velocities-from-issue.js, public/stateful-data/jira-data-requests.js, public/timeline-configuration/state-helpers.js, public/timeline-configuration/timeline-configuration.js, public/timeline-report.js
Adds a preliminary estimation report.  This report can help show how estimates are calculated.
=> some fixes, adding an estimate report

public/jira/rollup/dates/dates.ts, public/shared/main-helper.js, public/timeline-configuration/state-helpers.js, public/timeline-configuration/timeline-configuration.js, public/timeline-report.js
This removes the legacy velocity behavior.
=> Removing legacy velocity

public/jira/rollup/percent-complete/percent-complete.test.ts, public/jira/rollup/percent-complete/percent-complete.ts
update tests and reverse order of test input data
=> TR-22: Refactor rollup/percent-complete

public/react/SaveReports/components/SaveReportModal/SaveReportModal.test.tsx, public/react/SaveReports/components/SaveReportModal/SaveReportModal.tsx
=> TR-148: Select the report text when the modal opens

public/canjs/controls/select-issue-type/select-issue-type.js, public/canjs/controls/select-report-type/select-report-type.js, public/canjs/routing/data-utils.js, public/canjs/routing/route-data.js, public/timeline-report.js
NOTE: Review and merge #279 before reviewing this PR.
=> [TR-209] Move URL-linked data elements from select-report-type to route-data

public/canjs/controls/select-issue-type/select-issue-type.js, public/canjs/controls/select-report-type/select-report-type.js, public/canjs/controls/timeline-configuration/timing-calculation/timing-calculation.js, public/canjs/routing/data-utils.js, public/canjs/routing/route-data.js, public/timeline-report.js
NOTE: Review and marge #280 before reviewing this PR
=> [TR-207] Move route-linked data from timeline-configuration to route-data

public/canjs/controls/compare-slider.js, public/canjs/routing/route-data.js, public/shared/style-strings.js, public/stateful-data/jira-data-requests.js, public/timeline-report.js, public/utils/date/days-between.js, public/utils/date/local.js
You can now pick a specific date to compare to.
=> enabling the ability to set the comparison to a specific date

.github/workflows/deploy-prod.yaml, .github/workflows/deploy.yaml, .github/workflows/destroy-main-manual.yaml, .github/workflows/destroy-manual.yaml, .github/workflows/destroy-prod-manual.yaml
Changing the action version to use the tagged v1 version of the action. If subsequent minor fixes need to happen, they will be included.
=> Updating-action-reference

public/canjs/reports/gantt-grid.js, public/timeline-report.js
=> TR-229 Use 'not started' background color (and text color) for empty

public/canjs/reports/gantt-grid.js
=> TR-228 add ability to see children on grid hover

public/canjs/reports/gantt-grid.js
=> TR-228 add pointer to arrows and fix indentation

public/canjs/reports/gantt-grid.js, public/images/empty-set.svg
=> TR-235 fix the empty icon layout

public/canjs/reports/gantt-grid.js
=> TR-237 change now bar color

public/canjs/ui/autocomplete/autocomplete.js
the tooltip parent node can change, this accounts for this
=> fixing bug with tooltip

public/jira/rolledup/work-status/work-status.test.ts, public/jira/rolledup/work-status/work-status.ts, public/timeline-report.js
Will mark an issue as `completed` if the issue has a statusCategory of `Done`. Fixes some tests.
=> properly identifies epics in the status category of done

public/canjs/reports/gantt-grid.js, public/canjs/reports/scatter-timeline.js, public/react/StatusKey/StatusKey.tsx
=> Designed scatter plots 

playwright/auth.setup.ts
placeholder was removed. Still able to move forward with getByLabel
=> TR-309 e2e hanging tests

src/jira/rollup/historical-adjusted-estimated-time/actual-vs-estimated.ts, src/react/reports/EstimateAnalysis/TeamEstimateAccuracyVariance.tsx, src/react/reports/GroupingReport/components/SelectAggregator.tsx, src/react/reports/GroupingReport/ui/total-working-days-reducers.tsx, src/utils/date/business-days-inclusive.ts
Adds a max capacity aggregator that will tell teams the maximum amount of people on any one day
=> adds a max capacity
